# Generated by Django 3.1.2 on 2020-11-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('C', 'Cultural'), ('D', 'Diversión'), ('E', 'Educativo'), ('S', 'Social'), ('M', 'Musical'), ('D', 'Deportivo'), ('O', 'Otro')], default='C', max_length=1)),
                ('duracion', models.PositiveSmallIntegerField(default=120)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
    ]
