# Generated by Django 3.1.2 on 2020-11-05 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('numIdentificacion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipoIdentificacion', models.CharField(choices=[('C', 'Cédula de Ciudadanía'), ('E', 'Cédula de Extranjería'), ('P', 'Pasaporte'), ('O', 'Otro')], default='C', max_length=1)),
                ('apellidoPaterno', models.CharField(max_length=35)),
                ('apellidoMaterno', models.CharField(max_length=35)),
                ('nombres', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('X', 'Otro')], default='M', max_length=1)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.evento')),
            ],
        ),
    ]
