# Generated by Django 3.1.2 on 2020-11-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5)),
                ('sector', models.CharField(choices=[('V', 'Vip'), ('G', 'Gold'), ('P', 'Platinium'), ('G', 'General')], default='V', max_length=1)),
                ('nombre', models.CharField(max_length=30)),
                ('capacidad', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
